# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"

env:
  - TOXENV=py27-django18
  - TOXENV=py27-django19
  - TOXENV=py32-django18
  - TOXENV=py33-django18
  - TOXENV=py34-django18
  - TOXENV=py34-django19

before_install:
  - pip install codecov

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements_test.txt

# command to run tests using coverage, e.g. python setup.py test
# script: coverage run --source django_knowledgebase runtests.py
script: tox

after_success:
  - codecov
